config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "loans#new"

  resources :loans, only: %i[new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  include Business::Calculations

  def new
    @loan = Loan.new
  end

  def create
    loan = calculate_loan(loan_params[:purchase_price].to_f, loan_params[:arv].to_f)
    profit = calculate_profit(loan_params[:loan_term].to_i, loan, loan_params[:arv].to_f)
    all_loan_params = loan_params.merge({ loan:, profit: })

    @loan = Loan.new(all_loan_params)

    if @loan.save
      LoanMailer.with(loan: @loan).your_loan.deliver_later
      redirect_to loan_path(@loan)
    else
      render :new
    end
  end

  def show
    @loan = Loan.find(params[:id])
  end

  private

  def loan_params
    params.require(:loan).permit(:address, :loan_term, :purchase_price, :repair_price, :arv, :name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='bg-gray-100 w-full'>
  <head>
    <title>LoanCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='w-full'>
    <main class="flex w-full justify-center pt-24">
      <%= yield %>
    </main>
  </body>
</html>

app/views/loans/new.html.haml
.flex.flex-col.items-center.justify-center.bg-gray-300.overflow-y-scroll{ class: 'w-full', data: { controller: 'form' } }
  .flex.w-full.h-1.items-start.bg-gray-400.mb-12
    .loadbar.h-full{ data: { 'form-target': 'loadbar' } }
  = form_for @loan, html: { class: 'flex flex-col items-center w-full p-12'} do |form|
    .w-full.flex.flex-col.items-center{ data: { 'form-target': 'address' } }
      .w-full.text-start.italic.text-xl= 'What is your target property? (Address, City, State and Zip code)'
      = form.text_field :address, required: true, placeholder: 'Type your answer here...', autocomplete: 'off', class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
    .w-full.flex.flex-col.items-center.hidden{ data: { 'form-target': 'months' } }
      .w-full.text-start.italic.text-xl= 'How many months of loan do you require? (Up to 12 months)'
      = form.number_field :loan_term, required: true, placeholder: 'Type your answer here...', autocomplete: 'off', step: 1, class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
    .w-full.flex.flex-col.items-center.justify-between.hidden{ data: { 'form-target': 'purchase' } }
      .w-full.text-start.italic.text-xl= 'What are you buying the property for? Indicate property price'
      = form.number_field :purchase_price, required: true, placeholder: 'Type your answer here...', autocomplete: 'off', minimum: 0, step: 0.01, class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
    .w-full.flex.flex-col.items-center.justify-between.hidden{ data: { 'form-target': 'repair' } }
      .w-full.text-start.italic.text-xl= 'What is your repair budget?'
      = form.number_field :repair_price, required: true, placeholder: 'Type your answer here...', autocomplete: 'off', step: 0.01, class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
    .w-full.flex.flex-col.items-center.justify-between.hidden{ data: { 'form-target': 'arv' } }
      .w-full.text-start.italic.text-xl= "What is the property's After Repair Value(ARV)?"
      = form.number_field :arv, required: true, placeholder: 'Type your answer here...', autocomplete: 'off', step: 0.01, class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
    .w-full.flex.flex-col.items-center.justify-between.hidden{ data: { 'form-target': 'personal' } }
      .w-full.text-start.italic.text-xl= "Please give us your contact information"
      .flex.flex-col{ class: 'w-1/2' }
        .w-full.text-start.italic.text-xl.mt-4= form.label :name, 'Name:'
        = form.text_field :name, required: true, placeholder: 'Jane Doe', autocomplete: 'off', class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
      .flex.flex-col{ class: 'w-1/2' }
        .w-full.text-start.italic.text-xl.mt-4= form.label :email, 'Email:'
        = form.email_field :email, required: true, placeholder: 'john@doe.com', autocomplete: 'off', class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
      .flex.flex-col{ class: 'w-1/2' }
        .w-full.text-start.italic.text-xl.mt-4= form.label :name, 'Cellphone:'
        = form.text_field :phone, required: true, placeholder: '+1 (201) 95225264', autocomplete: 'off', class: 'p-2 border-0 bg-transparent border-b-2 border-gray-400 focus:border-gray-500 w-full text-2xl focus:ring-0'
      = form.submit 'Calculate', class: 'bg-custom-green text-2xl text-white p-4 rounded-xl mt-8'
    .w-full.flex.items-center.h-12
      .bg-red-700.hidden.p-2.text-white.rounded-xl{ data: { 'form-target': 'error' } }
    .w-full.flex.justify-center.h-24
      = button_tag 'Next', type: :button, class: 'bg-custom-green text-2xl text-white p-4 rounded-xl mt-8', data: { 'form-target': 'next', action: 'click->form#goToNext' }
  .w-full.text-red-500.mt-12
    - if @loan.errors.present?
      = @loan.errors.messages

app/views/loans/show.html.haml
.flex.flex-col.items-center.justify-center.bg-gray-300.p-6.rounded-xl{ class: 'w-1/2' }
  .font-bold.text-2xl.uppercase= 'This is your loan'
  .mt-24.w-full.flex.items-center.justify-between
    .border-gray-500.border-r.flex.flex-col.items-center.p-4{ class: 'w-1/2'}
      .w-full.flex.items-center.justify-between
        .font-bold= 'Name:'
        = @loan.name
      .w-full.flex.items-center.justify-between
        .font-bold= 'Email:'
        = @loan.email
      .w-full.flex.items-center.justify-between
        .font-bold= 'Phone:'
        = @loan.phone
      .w-full.flex.items-center.justify-between
        .font-bold= 'Address:'
        = @loan.address
      .w-full.flex.items-center.justify-between
        .font-bold= 'Loan term:'
        = @loan.loan_term
      .w-full.flex.items-center.justify-between
        .font-bold= 'Purchase Price:'
        = number_to_currency(@loan.purchase_price)
      .w-full.flex.items-center.justify-between
        .font-bold= 'Repair Price:'
        = number_to_currency(@loan.repair_price)
      .w-full.flex.items-center.justify-between
        .font-bold= 'ARV:'
        = number_to_currency(@loan.arv)
    .flex.flex-col.items-center.p-4{ class: 'w-1/2' }
      .text-2xl= 'The maximum loan is:'
      .text-3xl= @loan.loan
      .mt-12.text-xl= 'With a total profit of:'
      .text-xl= @loan.profit
      = '13% yearly interest'
  .font-bold.text-2xl.mt-12.hover:underline.font-bold= link_to 'New Loan', new_loan_path